janky release pipeline

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,13 +1,19 @@
 #===============================================================================
-# Build pipeline for pull requests
+# Build pipeline for releases
 #===============================================================================
-name: build
+name: release
 
 on:
-  push:
-    branches:
-    - main
-  pull_request:
+  workflow_dispatch:
+    inputs:
+      version:
+        description: "Version to release: format(vX.Y.Z) or shortcuts (major, minor, patch)"
+        type: string
+        default: "patch"
+      create_release:
+        description: "Whether to publish a GitHub Release"
+        type: boolean
+        default: false
 
 permissions:
   contents: write
@@ -15,10 +21,38 @@ permissions:
   packages: write
 
 jobs:
+  resolve-version:
+    runs-on: ubuntu-latest
+
+    outputs:
+      release_version: ${{ steps.set_version.outputs.release_version }}
+
+    steps:
+      - name: 📚 Checkout (GitHub)
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+
+      - name: Resolve version number
+        id: set_version
+        run: |
+          NEXT_VERSION=$(python .github/workflows/scripts/resolve_version.py "${{ github.event.inputs.version }}")
+          echo "Release version: $NEXT_VERSION"
+          echo "release_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
+
   build:
+    needs: [resolve-version]
+
     runs-on: ubuntu-latest
 
     steps:
+    - name: Validate on main branch for release creations
+      if: ${{ github.event.inputs.create_release == 'true' && github.ref != 'refs/heads/main' }}
+      run: |
+        echo "Error: a release can only be created from the main branch"
+        exit 1
+
     - name: 📚 Checkout (GitHub)
       uses: actions/checkout@v4
   
@@ -65,13 +99,23 @@ jobs:
     - name: 📚 Run tests
       run: make test
 
+    - name: 🏷️ Create a local release tag
+      run: |
+        declare -r TAG_NAME="${{ needs.resolve-version.outputs.release_version }}"
+
+        git tag -a ${TAG_NAME} -m "Release ${TAG_NAME}"
+
     - name: ghcr-login
-      if: startsWith(github.ref, 'refs/tags/v')
-      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
+      uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: 📦 Test release packaging
+    - name: 📦 Publish release
+      if: ${{ inputs.create_release == true }}
+      run: goreleaser --clean
+
+    - name: 📦 Publish release (snapshot)
+      if: ${{ inputs.create_release == false }}
       run: goreleaser --snapshot --clean
